version: "3.6"

services:
  fastapi:
    container_name: pm_fastapi
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "8000:8000"
    networks:
      - pmn
    depends_on:
      - db

  db:
    image: postgres:11-alpine
    container_name: pm_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - pmn

networks:
  pmn:
    driver: bridge
